CREATE TABLE IF NOT EXISTS public.celulares
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    almacenamiento integer NOT NULL,
    bateria integer NOT NULL,
    color character varying(50) COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    marca character varying(255) COLLATE pg_catalog."default" NOT NULL,
    modelo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    precio numeric(38,2) NOT NULL,
    stock integer,
    CONSTRAINT celulares_pkey PRIMARY KEY (id),
    CONSTRAINT celulares_almacenamiento_check CHECK (almacenamiento >= 0),
    CONSTRAINT celulares_bateria_check CHECK (bateria <= 100 AND bateria >= 0)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.celulares
    OWNER to postgres;

INSERT INTO celulares (marca, modelo, almacenamiento, color, bateria, precio, descripcion, stock)  VALUES

('Apple','iPhone 11',64,'Red',100,235,'',10),
('Apple','iPhone 11',64,'Black',100,235,'',10),
('Apple','iPhone 11',128,'Purple',100,255,'',10),
('Apple','iPhone 11',128,'White',100,255,'',25),
('Apple','iPhone 11',128,'Black',100,255,'',10),
('Apple','iPhone 11',128,'Black',100,255,'',10),

('Apple','iPhone 12',64,'White',86,265,'',10),
('Apple','iPhone 12',64,'Purple',87,265,'',10),
('Apple','iPhone 12',64,'Blue',87,265,'',10),
('Apple','iPhone 12',64,'Midnight',88,265,'',10),

('Apple','iPhone 12',128,'Blue',84,295,'',10),
('Apple','iPhone 12',128,'Purple',100,305,'',10),

('Apple','iPhone 12 Pro',128,'Golden',100,330,'',10),
('Apple','iPhone 12 Pro',256,'Blue',100,350,'',10),

('Apple','iPhone 12 Pro Max',128,'White',100,350,'',10),

('Apple','iPhone 13',128,'Midnight',83,355,'',10),
('Apple','iPhone 13',128,'Green',85,360,'',10),
('Apple','iPhone 13',128,'Red',88,375,'',10),
('Apple','iPhone 13',128,'White',92,390,'',10),
('Apple','iPhone 13',128,'Green',100,410,'Bateria Original',10),

('Apple','iPhone 13 Pro',128,'Blue Sierra',100,400,'no anda la camara 0,5',10),
('Apple','iPhone 13 Pro',128,'Silver',84,450,'',10),

('Apple','iPhone 13 Pro Max',128,'Green',81,480,'',10),
('Apple','iPhone 13 Pro Max',128,'Graphite',86,510,'',10),

('Apple','iPhone 14',128,'Blue',83,380,'',10),
('Apple','iPhone 14',128,'Purple',100,420,'',10),

('Apple','iPhone 14 Pro',128,'Purple',84,530,'',10),
('Apple','iPhone 14 Pro',128,'Black',86,560,'',10),

-- SAMSUNG
('Samsung','A16 5G',128,'Black',100,215,'',10),
('Samsung','A16 5G',128,'Blue',100,215,'',10),
('Samsung','A16 5G',128,'Light Gray',100,215,'',10),

('Samsung','A26 5G',256,'Mint Green',100,290,'',10),
('Samsung','A26 5G',256,'White',100,290,'',10),
('Samsung','A26 5G',256,'Black',100,290,'',10),

('Samsung','A36 5G',256,'Black',100,350,'',10),
('Samsung','A36 5G',256,'Lime',100,350,'',10),
('Samsung','A36 5G',256,'White',100,350,'',10),
('Samsung','A36 5G',256,'Lavender',100,350,'',10),

('Samsung','M55 5G',256,'Black',100,300,'',10),

('Samsung','S25 Ultra',256,'Black',100,1070,'',10),
('Samsung','S25 Ultra',256,'Gray',100,1070,'',10),
('Samsung','S25 Ultra',256,'White',100,1070,'',10),
('Samsung','S25 Ultra',256,'Silver',100,1070,'',10),

-- XIAOMI
('Xiaomi','Poco X6 Pro 5G',512,'Black',100,330,'',10),
('Xiaomi','Poco X6 Pro 5G',512,'Grey',100,330,'',10),

('Xiaomi','Poco X7 Pro 5G',512,'Black',100,395,'',10),
('Xiaomi','Poco X7 Pro 5G',512,'Green',100,395,'',10),

('Xiaomi','Redmi 14C',128,'Black',100,145,'',10),
('Xiaomi','Redmi 14C',128,'Blue',100,145,'',10),
('Xiaomi','Redmi 14C',128,'Green',100,145,'',10),

('Xiaomi','Redmi 14C',128,'Green',100,135,'',10),

('Xiaomi','Redmi 14C',128,'Green',100,150,'',10),
('Xiaomi','Redmi 14C',128,'Purple',100,150,'',10),

('Xiaomi','Redmi 14C',256,'Black',100,160,'',10),

('Xiaomi','Redmi Note 13 Pro 5G',256,'Black',100,305,'',10),

('Xiaomi','Redmi Note 14 4G',128,'Black',100,188,'',10),
('Xiaomi','Redmi Note 14 4G',128,'Green',100,188,'',10),
('Xiaomi','Redmi Note 14 4G',128,'Blue',100,188,'',10),

('Xiaomi','Redmi Note 14 4G',256,'Black',100,215,'',10),
('Xiaomi','Redmi Note 14 4G',256,'Lime Green',100,215,'',10),
('Xiaomi','Redmi Note 14 4G',256,'Ocean Blue',100,215,'',10),
('Xiaomi','Redmi Note 14 4G',256,'Gold',100,215,'',10),

('Xiaomi','14T Pro',512,'Black',100,660,'',10),
('Xiaomi','14T Pro',512,'Blue',100,660,'',10),
('Xiaomi','14T Pro',512,'Grey',100,660,'',10),

-- MOTOROLA
('Motorola','G04S',128,'Orange',100,140,'',10),

('Motorola','G15',256,'Green',100,175,'',10),
('Motorola','G15',256,'Grey',100,175,'',10),
('Motorola','G15',256,'Blazing Orange',100,175,'',10),

('Motorola','G75 5G',256,'Gray',100,260,'',10),
('Motorola','G75 5G',256,'Blue',100,260,'',10),
('Motorola','G75 5G',256,'Green',100,260,'',10),

('Motorola','G84 5G',256,'Marshmallow Blue',100,230,'',10),
('Motorola','G84 5G',256,'Midnight Blue',100,230,'',10),

-- INFINIX
('Infinix','Smart 9',128,'Black',100,135,'',10),
('Infinix','Smart 9',128,'Gold',100,135,'',10),
('Infinix','Smart 9',128,'Mint Green',100,135,'',10),
('Infinix','Smart 9',128,'Neo Titanium',100,135,'',10),

('Infinix','Hot 50I',256,'Sleek Black',100,155,'',10),

('Infinix','Hot 50 Pro',256,'Sleek Black',100,215,'',10),
('Infinix','Hot 50 Pro',256,'Titanium Gray',100,215,'',10),

('Infinix','Note 40 5G',256,'Obsidian Black',100,240,'',10),
('Infinix','Note 40 5G',256,'Titan Gold',100,240,'',10),

('Infinix','Note 50 Pro',256,'Black',100,305,'',10),
('Infinix','Note 50 Pro',256,'Purple',100,305,'',10),
('Infinix','Note 50 Pro',256,'Titanium Grey',100,305,'',10);